[package]
name = "hello-simple"
description = "Simple RUST example."
repository = "https://github.com/rajeshsola/rust-linux-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
